name: Pull Request Check

on: [ pull-request ]

jobs:
  react:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test:ci

  functions:
    name: Functions Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ./functions
        run: npm ci
      - name: Run Tests
        working-directory: ./functions
        run: npm run test:ci
