name: PROD Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Deploy
        run: npm run deploy -- --token=${{ secrets.FIREBASE_TOKEN }} --project=${{ secrets.PROJECT_ID }}
