# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: QA Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build-react:
    name: Build React
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-react
          path: build

  build-functions:
    name: Build Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: functions
        run: npm ci
      - name: Build
        working-directory: functions
        run: npm run build
      - name: Store Artifact
        working-directory: functions
        uses: actions/upload-artifact@v2
        with:
          name: build-functions
          path: build

  deploy-hosting:
    name: Deploy React
    needs: build-react
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-react
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_QA }}

  deploy-functions:
    name: Deploy Functions
    needs: build-functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-functions
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_QA }}
